# Generated by Django 3.1.7 on 2021-04-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20210404_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='shift_availability',
            field=models.IntegerField(choices=[(1, 'Morning Shift 5Am To 9Am')]),
        ),
    ]
